### ISSUE TITLE
https: needs to be removed from domain names

### ISSUE THREAD

**Issue by pqarmitage** [Sinfonietta/hostfiles#10]
In pronography-hosts, the following entries appear to need the `https:` to be removed:

127.0.0.1 https:bobs-tube.com
127.0.0.1 https:www.empflix.com
127.0.0.1 https:www.francodirect.com
127.0.0.1 https:www.hdpornt.com
127.0.0.1 https:www.mofozxxx.com

**Comment by Sinfonietta** [comment]
Thanks @pqarmitage, good catch.  Fixed.
