### ISSUE TITLE
more porn to block : By Dani

### ISSUE THREAD

**Issue by DaniV5** [Sinfonietta/hostfiles#103]
https://pornkai.com
https://sanctuary.in.net
http://www.funeralofsmiles.com/
[ literotica stuff ]
https://literotica.com/
https://shop.literotica.com/
https://www.literoticavod.com/
https://vipcams.literotica.com/
https://forum.literotica.com/

**Comment by Yodatoo** [comment]
https://www.boyfriendtv.com is already in.

**Comment by Danilopereira82** [comment]
remove it and add my link
its newer

**Comment by Yodatoo** [comment]
> 
> 
> remove it and add my link
> its newer

::scratch::

**Comment by Danilopereira82** [comment]
🙄 done

**Comment by Sinfonietta** [comment]
Tank you, these have been added.  Sorry for the very long delay.

**Comment by DaniV5** [comment]
no problem
take your time

**Comment by spirillen** [comment]
```shell
funeralofsmiles.com.    172800  IN      NS      expired1.hostgator.com.
funeralofsmiles.com.    172800  IN      NS      expired2.hostgator.com.
```
