### ISSUE TITLE
found more porn to block

### ISSUE THREAD

**Issue by Danilopereira82** [Sinfonietta/hostfiles#109]
https://www.xfantasy.com/
https://callista.su/
http://beasttracker.dog/
http://sxyprn.net/
https://www.xfantasy.com/
https://myporn.club/
https://sakuracircle.com/
http://bangextreme.se/
https://c.gorilandcomic.com/
https://gorilandcomic.com/
https://leporno.info
https://www.javlibrary.com
http://jav-legend.com/
http://funmwzj.net
http://www.sexinsex.net
http://www.freedl.org/
http://blogjav.net/
http://www.javjunkies.com
https://sakuracircle.com/
https://www.redgifs.com
https://monova.org
http://173.208.182.242/

**Comment by Sinfonietta** [comment]
Thank you @Danilopereira82 these are added.
