### ISSUE TITLE
Need to add “www." for some sites

### ISSUE THREAD

**Issue by Yodatoo** [Sinfonietta/hostfiles#110]
While testing, I realize that some sites work with and without "www.", e.g. viewgals.com. Although this domain is already in the master hosts file, it's still accessible, because somehow it still gets automatically resolved (not sure by the browser or website) to http://www.viewgals.com/ which isn't listed, and so not blocked.

**Comment by Sinfonietta** [comment]
@Yodatoo there is nothing magical about the "www."  It's just another subdomain.  Decades ago, for some reason, some domain admins used to use the "www" subdomain for serving web pages.  It was a silly fashion.  Nothing more, nothing less.

If a www subdomain needs to be blocked, then please let me know.  Just understand that "www.a.com" is no different than "abc.a.com".

**Comment by spirillen** [comment]
Try [rfc1630](https://tools.ietf.org/html/rfc1630)

Or from [RFC 3986](https://tools.ietf.org/html/rfc3986)

> most registered names beginning with "www" are likely to have a URI prefix of "http://"

let's also do a little simple test here and see which of the two lines below automatically gets turned into http(s) urls

mypdns.org

www.mypdns.org

## Conclusion
There is actually a RFC for usage of the `www.example.org` formatting for websites, and it's as I recall it over 20 years old, unfortunately I couldn't hit it in my search with in a decent time but it is there

but found a wiki that indicates I'm close in the ageing :smile: 26 years old 

<https://en.wikipedia.org/wiki/URL#cite_note-6>

You should also read up on <https://en.wikipedia.org/wiki/World_Wide_Web#WWW_prefix>

**Comment by Yodatoo** [comment]
I'm not familiar with all that. Maybe all that matters for now is include this:
www.viewgals.com
(although viewgals.com is already in).
