### ISSUE TITLE
new list 09/06/2020

### ISSUE THREAD

**Issue by Danilopereira82** [Sinfonietta/hostfiles#111]
https://bustyporn.com/
https://realpornclip.com/
https://xxxtor.com/
https://www.pornorip.biz/
http://pornotor.org/
http://pornolive.org/
http://pornleech.io
https://pornforall.net/
https://nyaa.net
https://www.sexy-pics.us/
https://onejav.com/
https://bbw-chan.nl
https://nudostar.com/
https://hentairead.com
http://xscandals.com/

**Comment by Sinfonietta** [comment]
Thank you @Danilopereira82 these are in now.  Sorry for the delay.
