### ISSUE TITLE
Some new hosts

### ISSUE THREAD

**Issue by MalteKiefer** [Sinfonietta/hostfiles#113]
alphaporno.com
analdin.com
anysex.com
apornstories.com
ashemaletube.com
bemyhole.com
bestfreetube.xxx
bigfuck.tv
bravoteens.com
de.xhamster.com
dirtypornvids.com
fantasti.cc
gotporn.com
hdsex.org
hog.tv
keekass.com
onlylesbiantube.com
porn.biz
porngo.com
pornkai.com
shemale.movie
shemalez.com
tranny.one
upornia.com
videos.apornstories.com
videosection.com
xxxfiles.com

**Comment by Danilopereira82** [comment]
most of the sites are already in the list

**Comment by Sinfonietta** [comment]
@Danilopereira82 I think these are all unique to my list.

**Comment by Sinfonietta** [comment]
Thank you @MalteKiefer these are added.

**Comment by MalteKiefer** [comment]
Thanks for your work!
