### ISSUE TITLE
Maybe remove rarbg from porn hosts?

### ISSUE THREAD

**Issue by caviidae** [Sinfonietta/hostfiles#116]
`rarbg.com`
`static.rarbg.com`
`www.rarbg.com`

RARBG is a generic torrent site. It does have a porn category but it is not the main focus of the site. (Not sure if that still counts for your list) It is also an outdated domain for RARBG anyway and redirects to the new one.

**Comment by Sinfonietta** [comment]
There's porn there.  Closing.
