### ISSUE TITLE
PORN sites

### ISSUE THREAD

**Issue by crssi** [Sinfonietta/hostfiles#118]
babes.com
brazzerscontent.com
hdpornhub.co
homemadegirlsporn.com
hotgaylist.com
icfcdn.com
mojoporntube.com
mypornhub.com
peeperz.com
phncdn.com
playboytv.com
pornflip.com
pornhub.net.co
pornhubuk.com
porniq.com
pornoscraper.com
pubnub.com
sexdesant.com
sextube.com
skipthegames.com
txxxsite.com
wareporn.com
whynotbi.com
xnxxii.com
xvideos-cdn.com
younggirlsfreeporn.com

**Comment by Sinfonietta** [comment]
Thank you @crssi these are added.

**Comment by crssi** [comment]
Thank you

I have made a mistake with `pubnub.com`.
It is not a `porn`, but other annoyance.

I am really sorry.

Cheers

**Comment by spirillen** [comment]
curl -I 'www.wareporn.com'
HTTP/1.1 301 Moved Permanently
Date: Wed, 09 Sep 2020 02:16:00 GMT
Connection: keep-alive
Cache-Control: max-age=3600
Expires: Wed, 09 Sep 2020 03:16:00 GMT
Location: https://www.loytube.com/

**Comment by crssi** [comment]
I have made a mistake with pubnub.com.
It is not a porn, please remove.

I am really sorry.

Cheers

**Comment by spirillen** [comment]
`sexdesant.com` seems rather dead...

![image](https://user-images.githubusercontent.com/44526987/98872286-920d0600-2476-11eb-9f67-2fcf7c4a540d.png)
