### ISSUE TITLE
false positive: monova.org

### ISSUE THREAD

**Issue by crssi** [Sinfonietta/hostfiles#119]
`monova.org` is not a `porn`, but a `torrent` site... see also https://github.com/nextdns/metadata/issues/372

please, remove form porn list

Thank you and cheers

**Comment by Sinfonietta** [comment]
I see a lot of porn there @crssi ...

**Comment by crssi** [comment]
Do you?
Now I am confused since I don't.
Do you have any screenshot, so I can easily reproduce here?

Cheers

**Comment by Sinfonietta** [comment]
@crssi really?

Steps to reproduce:

1. Go to https://monova.org.  Observe a search box.
2. In the search box, type "porn".  It brings you to https://monova.org/search?term=porn
3. Observe, pages of porn torrents to download.

Closing.

**Comment by crssi** [comment]
I have made a screen recording of your STR and I really cannot see any explicit porn media material on this page.
See [here](https://www.dropbox.com/s/xein3kob1blct5p/monova.mp4?dl=0).

But by this criteria the `google.com` and `duckduckgo.com` and similar should then also be on porn list?
A monova.org is a torrent search site where no such media is explicitly shown, where upper example and some other torrent search sites do show such media.

Cheers and stay healthy

**Comment by spirillen** [comment]
To be honest I would call it somewhere in between 

![image](https://user-images.githubusercontent.com/44526987/91638418-d0fef400-ea0f-11ea-9643-5ab650e3dd33.png)

For that I have made a specific list at <https://github.com/Clefspeare13/pornhosts/blob/master/submit_here/strict_adult.txt>

So users that would have zero access to any kind of adult related contents can those any of the strict lists, In this case I go with @crssi
