### ISSUE TITLE
2 url's to add into porn

### ISSUE THREAD

**Issue by crssi** [Sinfonietta/hostfiles#124]
phncdn.com
22pixx.xyz

Cheers

**Comment by spirillen** [comment]
Why is it you keeps trying to get `phncdn.com` into the lists??? 

The domain is useless unless your hosts file suddenly have started to support wildcards...

```shell
drill phncdn.com @ns1.dns.mypdns.org
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 14146
;; flags: qr rd ra ; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0 
;; QUESTION SECTION:
;; phncdn.com.  IN      A

;; ANSWER SECTION:
phncdn.com.     86400   IN      A       127.0.0.1
```

You can find the list of actually dumb hosts file required domains here: <https://www.mypdns.org/T1429>

**Comment by crssi** [comment]
Because every spouse of `pornhub.com` is using `phncdn.com` as a CDN and blocking it means breakage for those.

**Comment by spirillen** [comment]
> Because every spouse of `pornhub.com` is using `phncdn.com` as a CDN and blocking it means breakage for those.
> Oh, yes... I am using NextDNS.io and it takes that as a wildcard.

Exactly, you should only contribute it to wildcard list, adding it solely to a hosts file is going to give a lot of FN.

A example of that is this one <https://www.mypdns.org/source/PornRecords/browse/master/submit_here/adult.mypdns.cloud/wildcard.list$972>

You can use it by this link `https://www.mypdns.org/source/PornRecords/browse/master/submit_here/adult.mypdns.cloud/wildcard.list%24972?view=raw` as these wildcard list will enhange the DNS Load|lookup speed as they are smaller. You can also get it over RPZ :wink:

**Comment by crssi** [comment]
Thank you
