### ISSUE TITLE
bad website 

### ISSUE THREAD

**Issue by moongazer07** [Sinfonietta/hostfiles#130]
this website has lots of NSFW and gore and ear rape ear rape is a sound that is distorted and loud also it has porn possibly I haven't gone to the website because it's bad it also has flashing lights which can cause epilepsy seizures  the website is [kekma.ga](kekma.ga)

**Comment by Sinfonietta** [comment]
@moongazer07 kekma.ga does not resolve to a website.  So Iam closing this issue.
