### ISSUE TITLE
Mobile Version of the website Xhamster.com still displays Ads and they are not being blocked

### ISSUE THREAD

**Issue by Jpersh27** [Sinfonietta/hostfiles#131]
Hello @Sinfonietta 

I was referred to you by @StevenBlack and he said to bring the issue I am having to you because you are one of the porn extensions curators that they use for the host file lists.

1.) The issue I am having is that there are Ads not being blocked on the mobile version of the website xhamster.com

I am wondering if you could please review these 4 subdomains below and tell me if they are being blocked already or not and If they are not can they be added to the host file list?

0.0.0.0 lcdn.tsyndicate.com

0.0.0.0 collector.xhamster.com

0.0.0.0 video.xhcdn.com

0.0.0.0 tsyndicate.com

Thank you for your time.

**Comment by spirillen** [comment]
`tsyndicate.com` is all Adult Adware <https://www.mypdns.org/T2028>

`video.xhcdn.com` is the domain used for serving embedded videos by xhamster <https://www.mypdns.org/T2273>

`collector.xhamster.com` Is simply Tracking <https://www.mypdns.org/T2271>

**Comment by Sinfonietta** [comment]
@Jpersh27 thank you, done.  Thank you for the research @spirillen.
