### ISSUE TITLE
Additional porn hosts

### ISSUE THREAD

**Issue by IDKwhattoputhere** [Sinfonietta/hostfiles#15]
Some additional websites: [new.1.txt](https://github.com/Sinfonietta/hostfiles/files/1575801/new.1.txt)
Partially taken from: `https://en.wikipedia.org/wiki/MindGeek#Global_Alexa_ranks`

Seems to be used exclusively for sexual content (see [[NSFW](https://www.reddit.com/domain/vidble.com/)] (need to log in and display NSFW content)):
```
vidble.com
www.vidble.com
```

**Comment by Sinfonietta** [comment]
Thanks @IDKwhattoputhere !

**Comment by Sinfonietta** [comment]
Added!  Closing.

**Comment by IDKwhattoputhere** [comment]
Thanks for adding `vidble.com`. You seem to have missed these though(?):
> Some additional websites: new.1.txt

**Comment by IDKwhattoputhere** [comment]
I see you haven't added the ones from above. Here's two lists of new domains anyways. Hope they're more useful.
[gambling.txt](https://github.com/Sinfonietta/hostfiles/files/1791013/gambling.txt)
[porn.txt](https://github.com/Sinfonietta/hostfiles/files/1791014/porn.txt)
