### ISSUE TITLE
Invalid domain syntax (has a comma)

### ISSUE THREAD

**Issue by nicholashead** [Sinfonietta/hostfiles#152]
The pornography-hosts file has this line:

`0.0.0.0 desi.lustflix,in`

Which is invalid syntax, and I'm guessing should be `0.0.0.0 desi.lustflix.in`

**Comment by Sinfonietta** [comment]
thank you @nicholashead fixed!

**Comment by spirillen** [comment]
it's apparently not the only one.... 

Pyfunceble found this one on your porn list `chat.chaturbate.lusecurity`

and this one somewhere else 
```
Subject                                                                                              Status      Source    
---------------------------------------------------------------------------------------------------- ----------- ----------
pornsites.xx                                                                                         INVALID     SYNTAX    
xscandals.com/                                                                                       INVALID     SYNTAX

```

Try to run PyFunceble against your list some time.

`pyfunceble -f https://raw.githubusercontent.com/Sinfonietta/hostfiles/master/pornography-hosts https://raw.githubusercontent.com/Sinfonietta/hostfiles/master/gambling-hosts https://raw.githubusercontent.com/Sinfonietta/hostfiles/master/snuff-hosts https://raw.githubusercontent.com/Sinfonietta/hostfiles/master/social-hosts --display-status INVALID --syntax --no-files`
