### ISSUE TITLE
Question: How do you sort the files?

### ISSUE THREAD

**Issue by irimi1** [Sinfonietta/hostfiles#154]
Hi! I’m collecting a few pornography hosts that aren’t blocked yet (and also not in StevenBlack’s porn hosts file, which uses this one), and don’t want to sort the entries by hand. Using the Linux 'sort' command, I can’t reproduce the order currently used, meaning I can’t sort without reordering existing entries.
So how to I reproduce the current entry order, if not using the 'sort' command?

**Comment by Sinfonietta** [comment]
@irimi1 I sometimes use Ghosts which has a really nise sort option that sorts by domain, then tld, then subdomain, then subdomain.subdomain, etc.

https://github.com/StevenBlack/ghosts

**Comment by irimi1** [comment]
Oh cool, thanks for pointing me to it! This is going to help me avoid chaotic additions to the list :)
