### ISSUE TITLE
pornography-hosts breaking Twitter

### ISSUE THREAD

**Issue by lazios** [Sinfonietta/hostfiles#177]
I just noticed that my Twitter was broken (being more specific, images aren't loading at all). Since I use Steven Black's Unified Hosts with the porn extension, I began searching for the issue. I quickly found out that the domain "pbs.twimg.com" was being blocked and therefore breaking Twitter. Digging deeper, the domain was added because your blocklist is one of many being used to gather the whole hostlist. 

The commit 6fe384205c4aa35ba862487aa42556b2bfc03e8e with the title "Merge pull request #69 from 1boii/porn-hosts" introduced the block of "pbs.twimg.com" I would appreciate it if you could fix that
![twitter](https://user-images.githubusercontent.com/92884195/153728548-c37b1b0d-2900-4577-a47f-047c97be1c90.png)
.

**Comment by Sinfonietta** [comment]
Thank you @lazios I just fixed this.
