### ISSUE TITLE
ponography-hosts breaking imgur

### ISSUE THREAD

**Issue by willisrm** [Sinfonietta/hostfiles#180]
Hey, I just discovered the same problem as Lazios found in issue #177 due to the same circumstances of propagation up to Steven Black's Unified Hosts with porn extension, only with i.imgur.com being added as well, which breaks a non-trivial percentage of image hosting with the regular internet, including parts of Reddit and countless community forums. The problem stems from the same commit https://github.com/Sinfonietta/hostfiles/commit/6fe384205c4aa35ba862487aa42556b2bfc03e8e that merged the hosts file submitted by @1boii

Upon closer inspection of their 55kb hosts file, I noticed in addition to the two major internet breaking subdomain inclusions of pbs.twimg.com and i.imgur.com, there are a lot of redundant language/region subdomains for known existing mainstream pornography domains already blocked in your own hosts file, multiple user subdomain inclusions for other lesser known pornography domains, and a substantial inclusion of several .XXX and .PORN TLDs, which seems... redundant. I appreciate their effort to help, but I suspect at least a quarter of the entries could be easily removed without any loss of blocked domains in their own hosts file on its own, and considerably more when merged with your own.

Given the size and somewhat bloated/redundant quality of the imported list in light of its inclusion of more than one legitimate subdomain, and how many routers are limited in how large their hosts files can be, I'm politely requesting that you refrain from further inclusion of the 1boii/hosts list until a full review of their hosts file with considerable improvement in size reduction and quality is made.

**Comment by Sinfonietta** [comment]
I agree with this.

**Comment by Sinfonietta** [comment]
Fixed.
