### ISSUE TITLE
Adding More Porn Sites

### ISSUE THREAD

**Issue by g1t3m** [Sinfonietta/hostfiles#200]
Hello @Sinfonietta! I came across a few more sites that should be added to the porn filter:
cambeauties.com
kawaiifu.com
thothub.is
thothub.su
jable.tv
3hentai.net
xxxfree.watch
crockotube.com
maturehits.com
fphentai.com
bestanime3.xyz
redbeeg.com
theporndude.fun
namethatpornad.com
slayed.com

**Comment by Sinfonietta** [comment]
These have been added thank you!
