### ISSUE TITLE
Two more porn sites 

### ISSUE THREAD

**Issue by NeedingMuchHelp** [Sinfonietta/hostfiles#215]
Hi @Sinfonietta

Could you please block these two:
Ehentai.to
Nhentai.to

Regarding the second one - I was able to manually block the first by downloading Steve Black's host file and adding the "0.0.0.0 ehentai.to" line. However, when I try the same with the second, it does not block!

When you add these to the list, would you be able to check that the second one works? And if it doesn't work the normal way, could you let me know how to get it working so I can continue to customise my hosts file?

**Comment by Sinfonietta** [comment]
Thank you @NeedingMuchHelp I have added these.
