### ISSUE TITLE
Porn

### ISSUE THREAD

**Issue by ghost** [Sinfonietta/hostfiles#216]
flirt.com
friendfinder-x.com
bdsmdatingonly.com
match.com
bdsmdatingsites.co.uk
wiccadating.com
dateawiccan.com
wiccanpersonals.com
wiccandatingsite.com
bdsmdatingchat.com
bondagepal.com
bdsmdate.com
mybdsmhookups.com
bdsmu.com
fetster.com
bondagedating.com
kinkdapp.com
perfect.is

**Comment by Sinfonietta** [comment]
@gita6t5 match.com is just a dating site, not porn.
