### ISSUE TITLE
instagram-jtadnet.com

### ISSUE THREAD

**Issue by SAMJEN22** [Sinfonietta/hostfiles#231]
instagram-jtadnet.com

_Originally posted by @SAMJEN22 in https://github.com/Sinfonietta/hostfiles/issues/105#issuecomment-1482330528_

**Comment by SAMJEN22** [comment]
> 

![Screenshot_20230305_184858_Chrome](https://user-images.githubusercontent.com/128782955/227446336-09a4748e-2150-400a-8ef7-2e063f8e04f6.jpg)

**Comment by Sinfonietta** [comment]
@SAMJEN22 can you explain? I do not understand. The screen shot is not the domain you suggest.
