### ISSUE TITLE
New pornlist inclusion

### ISSUE THREAD

**Issue by jobbb2** [Sinfonietta/hostfiles#243]
Hello, please add it to the porn list. Thank you. Best regards

127.0.0.1 erotik.markt.de
127.0.0.1 www.frauensuchen.ch
127.0.0.1 austria.sexfeuer.com
127.0.0.1 cz.xhopen.com
127.0.0.1 farmhub.net
127.0.0.1 www.xnightflight.com
127.0.0.1 www.nftpussies.com
127.0.0.1 e-kondomy.cz
127.0.0.1 www.oolveri.com
127.0.0.1 erotikfilme.fun
127.0.0.1 lu.xporno.me
127.0.0.1 cartoonporn.pro
127.0.0.1 www.madame-ellen.com
127.0.0.1 xchica.com
127.0.0.1 www.ujizz.xxx
127.0.0.1 www.xxxtube1.com
127.0.0.1 www.multi.xxx
127.0.0.1 pornxo.xxx
127.0.0.1 www.xxxpornxxx.net
127.0.0.1 xxxgr.net
127.0.0.1 xxx-porn-hub.com
127.0.0.1 clipsbai.com
127.0.0.1 yourxxxvideos.pro
127.0.0.1 en.perdos.de
127.0.0.1 x-xx.pro
127.0.0.1 www.voyeurxxxsex.com
127.0.0.1 www.xxxvideo.tube
127.0.0.1 xxxvidso.com
127.0.0.1 www.pornid.name
127.0.0.1 xmxx.click
127.0.0.1 www.porno-zona.com
127.0.0.1 www.pornflix.to
127.0.0.1 www.clip2vip.com
127.0.0.1 mlabstores.com
127.0.0.1 japanesehdvideos.com
127.0.0.1 porndasi.cc
127.0.0.1 wildpornvideos.cc
127.0.0.1 xxxgo.cc
127.0.0.1 redxxxvideo.net
127.0.0.1 xxxvideo247.cc
127.0.0.1 bizarr.date
127.0.0.1 www.fick-markt.com
127.0.0.1 deutsche-sex.com
127.0.0.1 omas-suchen-sex.com
127.0.0.1 scheissegalien.com
127.0.0.1 www.sextermedia.com
127.0.0.1 www.schwanzkanone.com
127.0.0.1 allesporno.net
127.0.0.1 www.pornopiraten.xxx
127.0.0.1 moesensex.net
127.0.0.1 sexgifs.me
127.0.0.1 bestgermanporn.com
127.0.0.1 ichmussmalpipi.com
127.0.0.1 geile-amateure.org
127.0.0.1 xxxwap.mobi
127.0.0.1 xspiel.com
127.0.0.1 ganstagirls.com
127.0.0.1 pornohirsch.online
127.0.0.1 redxxx.cc

**Comment by Sinfonietta** [comment]
@jobbb2 why do you make so many issues? You can put everything in one issue. You can edit an issue you have created. I am gonna add these but please, in the future, make it easy for me.

**Comment by Sinfonietta** [comment]
Done, closing.

**Comment by jobbb2** [comment]
> @jobbb2 why do you make so many issues? You can put everything in one issue. You can edit an issue you have created. I am gonna add these but please, in the future, make it easy for me.

Thats a good idea, thank you.

**Comment by jobbb2** [comment]
Hello https://github.com/Sinfonietta. When will the changes in the porn filter list be available for everyone?
