### ISSUE TITLE
More gambling sites

### ISSUE THREAD

**Issue by mrkevlh** [Sinfonietta/hostfiles#26]
www.betonline.com
www.sportsbook.ag
www.lasvegassportsbetting.com
www.oddsshark.com
betting.betfair.com
www.offtrackbetting.com
m.skybet.com
sports.williamhill.com
vegas.williamhill.com
macau.williamhill.com
casino.williamhill.com
livecasino.williamhill.com
games.williamhill.com
bingo.williamhill.com
poker.williamhill.com
www.sportsbettingdime.com
www.sunbets.co.uk
www.sportsbookreview.com
www.pinnacle.com
sblp.intertops.eu
www.justbet.co
www.wagerweb.eu
danskespil.dk
www.bodog888.com
sports.bwin.com
global.138.com
www.winner.co.uk
en.expekt.com
sports.gamebookers.com
en.betclic.com
www.cloudbet.com
www.betcoin.ag
www.jetwin.com
www.bitcoinrush.io
sportsbet.io
betregal.com
www.betmonarch.com
www.betcruise.com
www.northbet.com
mybookie.ag
m.jetbull.com
www.betodds.ag
www.betplatinum.ag
www.gamingclub1.com
www.betmylines.com
www.alohasportsbook.com
www.bet2win.ag
www.bigcitysportsbook.com
balkanbet.co.rs
sport.netbet.co.uk
jojobet.com
betdna.com
www.parimatchplay1.com
www.actionbets.com
www.azcasino.com
sports.br.betboo.com
www.betsbc.com
www.linesmaker.eu
www.playersonly.ag
www.superbook.ag
www.mpcasino.com
www.vacasino.com
www.gotoentertainment.com
www.casinony.com
www.japancasino.com
www.dccasino.com
www.mexicocasino.com
www.bamasportsbook.com
www.indycasino.com
www.12bet.uk
www.wagerup.eu
www.crsportsbet.ag
zenitbet.com
www.admiralspot.com
www.livesports.ag
www.10bet.co.uk
www.mrgreen.com
casino.betway.com
livecasino.betway.com
sports.betway.com
vegas.betway.com
poker.betway.com
plus.betway.com
m.boylesports.com
www.karamba.com
www.unibet.co.uk
www.grosvenorcasinos.com
www.royalpanda.com
livebetting.bwin.com
thebettingguy.co.uk
www.betstars.uk
www.pokerstarscasino.uk
www.pokerstars.uk
www.uk-k8.com
energybet.com
wwin.com
www.stakers.com
www.32red.com
www.marathonbet.co.uk
sports.gentingcasino.com
www.redzonesports.bet
sports.vernons.com
casino.vernons.com
bingo.vernons.com
www.bethard.com

**Comment by Sinfonietta** [comment]
Thank you @mrkevlh these are added in commit f31ce8124b72d1449370085aa16056a6ab0e5038.
