### ISSUE TITLE
Broken domains

### ISSUE THREAD

**Issue by DemurestPie** [Sinfonietta/hostfiles#262]
I found some more broken domains in the porn list:

Line 2183:  0.0.0.0 beeg.globa0.0.0.0 1
Line 10707:  0.0.0.0 momandsons0.0.0.0 ex.pro
Line 20291:  0.0.0.0 www.freierporno.mobi0.0.1 www.sadnewsex.com
Line 22085:  0.0.0.0 www.pornz.com.e

**Comment by garyn87048** [comment]
I didn't see this open issue and #265 also covers the first two lines.

**Comment by DemurestPie** [comment]
Looks like the first two domains were fixed by c79c309278083dd70b1a95f63a4257c97d6e6b51

The other two domains still appear to be broken

**Comment by Sinfonietta** [comment]
These were fixed a while ago.
