### ISSUE TITLE
two lines from either gambling-hosts or porn-hosts causing issues in pfsense

### ISSUE THREAD

**Issue by garyn87048** [Sinfonietta/hostfiles#265]
StevenBlack combines the gambling and porn lists into one gambling-porn list which users are pulling into pfsense.  The combined list contains two lines which are causing issues in pfsense.  This is related to issue https://github.com/StevenBlack/hosts/issues/2478

After parsing, the two lines appear in pfsense as:

- `momandsons0.0.0.0 60 IN A 10.10.10.1`
- `beeg.globa0.0.0.0 60 IN A 10.10.10.1`

When these lines are deleted, pfsense parses the list without errors.

Thanks!

Gary

**Comment by Sinfonietta** [comment]
This is fixed! Thank you.
