### ISSUE TITLE
1 Porn Whitelist

### ISSUE THREAD

**Issue by jobbb2** [Sinfonietta/hostfiles#281]
Porn - W H I T E L I S T:
Please do not block the following website:

streamvid.net

**Comment by thomasmerz** [comment]
Can you add a screenshot to prove it's not porn at all?

**Comment by jobbb2** [comment]
yes, one moment. sure

**Comment by jobbb2** [comment]
its only for streaming 
![Bildschirmfoto_2023-12-18_23-17-35](https://github.com/Sinfonietta/hostfiles/assets/85370121/652881b0-9da2-407f-ad9e-f316595f604f)

click on "STREAMVID HD".... and then its blocked by you

**Comment by O11iee** [comment]
These streaming sites allow porn, commonly used for OnlyFans leaks and other premium porn as they are DMCA ignored.

**Comment by jobbb2** [comment]
Hello, @O11iee. Please can you send me an example for OnlyFans leaks or other premium porn with this domain. Thank you. Best regards

**Comment by O11iee** [comment]
https://www.wjunction.com/threads/streamvid-net-daily-payouts-bonuses-75-10k-paying-highest-for-tier-4-1080-fast-hls-video-streaming.259978/

"adult content allowed" also the fact that they have a stripchat affiliate whitelabel in their header gives it away ^^

**Comment by jobbb2** [comment]
ok. i have read an confirmation about porn.

An active member wrote: Yes. Porn is allowed. Legal adult means no porn like childporn etc

I close it. Best regards
