### ISSUE TITLE
Add to Gambling

### ISSUE THREAD

**Issue by mirokrastev** [Sinfonietta/hostfiles#316]
As per StevenBlack's request, I'm pinging you @Sinfonietta about these sites:
[www.palmsbet.com](http://www.palmsbet.com/)
[www.betano.bg](http://www.betano.bg/)
[www.pokerstars.bg](http://www.pokerstars.bg/)
everbet.bg
slotino.bg

Original GH Issue: https://github.com/StevenBlack/hosts/issues/2648

**Comment by Sinfonietta** [comment]
Thank you @mirokrastev this is done.
