### ISSUE TITLE
[Add request] Various porn websites

### ISSUE THREAD

**Issue by dotshe** [Sinfonietta/hostfiles#318]
These urls can be added to the list of porn sites

https://madou.club/
http://hsck3.com/
http://69vods.com/
http://www.by2297.com/
https://tssba10.com/
https://nn21.tv/
https://17c455.com/ (only visible on mobile)

Thank you for your work

**Comment by Sinfonietta** [comment]
Thank you @dotshe I have added these.

**Comment by dotshe** [comment]
Thank you.
