### ISSUE TITLE
Adding a list of escort website

### ISSUE THREAD

**Issue by zinnwaldite** [Sinfonietta/hostfiles#328]
In addition to blocking pornography, I would suggest to add escort dating website which also provide graphic content and promote paid-sexual activities (illegal in many countries).

Here is a small list of mostly european-referenced sites:

ladyxena.com
tescort.com
sexemodel.com
1baiser.com
6annonce.net
wannonce.com
escorte.com
escortsexe.net
lovesita.com
escort46.fr
escorts69.fr
scort.fr
shopescort.net
escortfr.net
medusa-escort.fr
fgirl.ch
topescortbabes.com
escortnews.com
eurogirlsescort.com
eurogirlescort.com
quartier-rouge.be
renole.com
sabrinabattagliola.it
planetescort.com
realescort.eu
escortandbabes.com.au
escort-ireland.com
happyescorts.com
escort-side.dk
gemidos.tv
allo-escort.com
zaramodel.com
franceescortguide.com
escortfrance.fr
rent.men
the-harem.com
hotvipescort.com
celibook.com
atlasescorts.com
allomodel.com
topescort.com
ts-dating.com
planescort.com
xlamma.com

Cheers!

**Comment by Sinfonietta** [comment]
Thank you @zinnwaldite I add these in commit 241e7e9386
