### ISSUE TITLE
Re-evaluate `*.blogspot.com` and `*.tumblr.com` domains

### ISSUE THREAD

**Issue by StevenBlack** [Sinfonietta/hostfiles#334]
Hi @Sinfonietta!

In other porn lists I just purged a bunch of `*.blogspot.com` and `*.tumblr.com` domains and I'm wondering if you might consider doing the same?

Both Blogger and Tumblr have been doing content moderation for quite a long time now, and I've found that so many sketch Blogger sites are 404 now...

Cheers!

**Comment by Sinfonietta** [comment]
Thank you @StevenBlack I agree and I have made these changes.
