### ISSUE TITLE
Alternative domains for already reported sites

### ISSUE THREAD

**Issue by matteocoder** [Sinfonietta/hostfiles#38]
Hello @Sinfonietta , these sites have already been added to your list in the past with a "www." prefix, but unfortunately they are still accessible if you type the address without it:

```
girlspoppingballoons.com
girlsgonehypnotized.com
girlsgettingsleepy.com
girlsbarefoot.com
```
Thanks for maintaing this list.

**Comment by Sinfonietta** [comment]
Thank you @matteocoder these have been added.
