### ISSUE TITLE
More porn domains 

### ISSUE THREAD

**Issue by helpingsometimes** [Sinfonietta/hostfiles#43]
0.0.0.0 www.xvideoporno.tv
0.0.0.0 xvideos10.blog.br
0.0.0.0 pornotube.blog.br
0.0.0.0 xvideos.blog
0.0.0.0 xvideos.blog.br
0.0.0.0 xvideosamadoras.com
0.0.0.0 www.porntv.com
0.0.0.0 toppornsites.com
0.0.0.0 www.pornobengala.com
0.0.0.0 porn.es
0.0.0.0 24porn.com
0.0.0.0 vtrahetut.porn
0.0.0.0 masseurporn.com
0.0.0.0 www.tangoporno.com
0.0.0.0 www.sexloving.net
0.0.0.0 teenfuckhd.com
0.0.0.0 www.bitchyourfamous.com
0.0.0.0 indianporn.xxx
0.0.0.0 pornxxxvideos.net
0.0.0.0 www.hdporzo.com
0.0.0.0 www.filmespornos.net
0.0.0.0 beastiegals.com
0.0.0.0 mrdeepfakes.com
0.0.0.0 freepornq.com
0.0.0.0 pretty.porn
0.0.0.0 www.18porn.sex
0.0.0.0 happy-porn.com
0.0.0.0 www.mrvideosdesexo.xxx
0.0.0.0 mobileporn.me
0.0.0.0 www.wowgirlsblog.com
0.0.0.0 www.pornid.xxx
0.0.0.0 www.picspussy.com
0.0.0.0 www.maturemomson.com
0.0.0.0 www.hotgaylist.com
0.0.0.0 porn555.com
0.0.0.0 zpornz.com
0.0.0.0 yps.to
0.0.0.0 youporner.red
0.0.0.0 youfreeporntube.net
0.0.0.0 yesporner.co
0.0.0.0 yarada.ru
0.0.0.0 xxxstreams.info
0.0.0.0 xxx.youfreeporntube.net
0.0.0.0 xvideos4u.com
0.0.0.0 xvideos4u.org
0.0.0.0 xtasie.com
0.0.0.0 xpornrbg.com
0.0.0.0 xopenload.video
0.0.0.0 www.xmovieshub.com

**Comment by Sinfonietta** [comment]
Thank you @helpingsometimes this is implemented in commit 8b7252108e03ae1d849956bd255eaa4af3822b0d.
