### ISSUE TITLE
"Anything goes" video hosters

### ISSUE THREAD

**Issue by paxperscientiam** [Sinfonietta/hostfiles#51]
Hey @Sinfonietta ! What's your opinion on "anything goes"  video hosts? I'm referring to sites that are neutral / indifferent to the nature of the content they host. For instance, https://mixtape.moe.

Should such sites be considered? If so, for which category?

Take care.

**Comment by Sinfonietta** [comment]
That's site has some awful stuff.

I already classify mixtape.moe as a "snuff" host.  I think others have it as a porn site too.

**Comment by paxperscientiam** [comment]
Got it. In the future, I will also submit "anything goes" content hosts for consideration.
