### ISSUE TITLE
Porn domains

### ISSUE THREAD

**Issue by mhpj6l9wbxwm** [Sinfonietta/hostfiles#61]
Please add the following porn domains to the list. I've done my best to include or exclude `www.` only where necessary.

```
127.0.0.1 xmoviesforyou.com
127.0.0.1 de.pornhub.com
127.0.0.1 ci.phncdn.com
127.0.0.1 de.redtube.com
127.0.0.1 ei-ph.rdtcdn.com
127.0.0.1 devporn.net
127.0.0.1 www.devporn.net
127.0.0.1 www.ultrahdporn.eu
127.0.0.1 pornlovo.co
127.0.0.1 www.pornlovo.co
127.0.0.1 www.pornmega.com
127.0.0.1 www.ebalovo.mobi
127.0.0.1 namethatpornstar.com
127.0.0.1 www.namethatpornstar.com
127.0.0.1 www.realteengirls.com
127.0.0.1 www.freeones.co.cr
127.0.0.1 www.freeones.ru
127.0.0.1 dailyporntv.com
127.0.0.1 www.dailyporntv.com
127.0.0.1 datoporn.co
127.0.0.1 cnx.datoporn.co
127.0.0.1 www.indexxx.com
127.0.0.1 javporn.co
127.0.0.1 redporny.com
127.0.0.1 zlesbian.com
127.0.0.1 milfhd.net
127.0.0.1 mompornos.com
127.0.0.1 stepfamilys.com
127.0.0.1 cutycam.com
127.0.0.1 hdsexporn.org
127.0.0.1 pornoindian.net
127.0.0.1 pornoasia.org
127.0.0.1 bestblackporn.net
127.0.0.1 hdporner.co
127.0.0.1 javhd3.co
127.0.0.1 tubegals.live
127.0.0.1 yesporn.website
127.0.0.1 ixxxporn.top
127.0.0.1 elephanttube.info
127.0.0.1 filmeporno3.top
127.0.0.1 lobstertube.club
127.0.0.1 xxnxx3.club
127.0.0.1 dinotube.club
127.0.0.1 porn143.com
127.0.0.1 apetube.rocks
127.0.0.1 tubegalore.online
127.0.0.1 sexxxxx.top
127.0.0.1 phimsexx.top
127.0.0.1 tryteens.com
127.0.0.1 spyfams.com
127.0.0.1 www.myyouporn.com
127.0.0.1 babe.today
```

**Comment by Sinfonietta** [comment]
Thank you @mhpj6l9wbxwm these are added in commit 2e62ccd8a3f3d75f63d7d8f387e27e3cbd54bcaa

**Comment by bonusn** [comment]
0.0.0.0 londep18.com
0.0.0.0 vlphimsex.net
0.0.0.0 sexdep.pro
0.0.0.0 kichduc.cc
0.0.0.0 allx.tv
0.0.0.0 javhdhay.net
0.0.0.0 xvidzz.com
0.0.0.0 jav21.net
0.0.0.0 3xhd.tv
0.0.0.0 cu3x.net
0.0.0.0 xnxx113.com
0.0.0.0 londep.pro
0.0.0.0 xnxx1.net
0.0.0.0 emsex.net
0.0.0.0 pornhvideos.net
0.0.0.0 phim.sex
0.0.0.0 jav69.net
0.0.0.0 websexgay.com
0.0.0.0 phimsexonlines.com
0.0.0.0 javzz.net
0.0.0.0 soc3x.com
0.0.0.0 sexhihi.net
0.0.0.0 lauxanh.org
0.0.0.0 phimsec.pro
0.0.0.0 javhd.pro
0.0.0.0 vlxx.tv
0.0.0.0 jav321.net
0.0.0.0 ditvl.net
0.0.0.0 kichduc.me
0.0.0.0 vuasex.net
0.0.0.0 sexhayvl.pro
0.0.0.0 phimsex3d.com
0.0.0.0 phimsexvip.mobi
0.0.0.0 phimsex1.net
0.0.0.0 duccai.com
0.0.0.0 phimsd.org
0.0.0.0 javforme.ninja
0.0.0.0 javforme.com
0.0.0.0 sextop1.net
0.0.0.0 sex5.pro
0.0.0.0 sex88.net
0.0.0.0 sexhay69.net
0.0.0.0  javphim.net
0.0.0.0 www.emsex.net
0.0.0.0 www.pornhvideos.net
0.0.0.0 www.phim.sex
0.0.0.0 www.jav69.net
0.0.0.0 www.websexgay.com
0.0.0.0 www.allx.tv
0.0.0.0 www.phimsexonlines.com
0.0.0.0 www.sexdep.pro
0.0.0.0 www.javzz.net
0.0.0.0 www.soc3x.com
0.0.0.0 www.javhdhay.net
0.0.0.0 www.duccai.com
0.0.0.0 www.sexhihi.net
0.0.0.0 www.phimsec.pro
0.0.0.0 www.xvidzz.com
0.0.0.0 www.jav21.net
0.0.0.0 www.javhd.pro
0.0.0.0 www.vlxx.tv
0.0.0.0 www.jav321.net
0.0.0.0 www.ditvl.net
0.0.0.0 www.kichduc.me
0.0.0.0 www.kichduc.cc
0.0.0.0 www.vuasex.net
0.0.0.0 www.sexhayvl.pro
0.0.0.0 www.phimsex3d.com
0.0.0.0 www.phimsexvip.mobi
0.0.0.0 www.phimsex1.net
0.0.0.0 www.lauxanh.org
0.0.0.0 www.phimsd.org
0.0.0.0 www.sextop1.net
0.0.0.0 www.javforme.ninja
0.0.0.0 www.javforme.com
0.0.0.0 www.vlphimsex.net
0.0.0.0 www.3xhd.tv
0.0.0.0 www.sex5.pro
0.0.0.0 www.sex88.net
0.0.0.0 www.sexhay69.net
0.0.0.0 www.javphim.net
0.0.0.0 www.xnxx1.net
0.0.0.0 www.londep.pro
0.0.0.0 www.xnxx113.com
0.0.0.0 www.cu3x.net
0.0.0.0 www.londep18.com

**Comment by bonusn** [comment]
block porn vietnamese
