### ISSUE TITLE
more porn to block

### ISSUE THREAD

**Issue by Danilopereira82** [Sinfonietta/hostfiles#68]
https://incognitymous.com/
https://www.ohentai.org/
https://ecchi.iwara.tv
https://dark.moe
https://www.mulsanyang5.com/
https://cangku.moe/
https://mantis-x.net/
https://rule-34.net
https://rule34.xyz/
https://www.r34anim.com
https://rule34gifs.com/
https://rule34.top/
https://rule34hentai.com/
https://scrolller.com/
https://m.3movs.com
https://smutba.se

**Comment by Sinfonietta** [comment]
Thank you @Danilopereira82, I have added these to the list.

**Comment by spirillen** [comment]
Without checking your hosts file i stumbled on this `iwara.tv` as i was adding these to my RPZ zones

just to be friendly if you was stumbled on it your self

**Comment by Danilopereira82** [comment]
what?

iwara.tv has some sexy stuff but  its not for porn
ecchi.iwara.tv is exclusively made for it

**Comment by spirillen** [comment]
Super, thx for the update, I modify my [records](https://gitlab.com/my-privacy-dns/matrix/matrix/issues/589) and ticket
