### ISSUE TITLE
Metadata for your hosts?

### ISSUE THREAD

**Issue by StevenBlack** [Sinfonietta/hostfiles#7]
Hi @Sinfonietta,

My hosts repo now enumerates information about its various sources, including those from this repo.

Can you please look [here](https://github.com/StevenBlack/hosts/blob/master/extensions/gambling/update.json), [here](https://github.com/StevenBlack/hosts/blob/master/extensions/porn/update.json), and [here](https://github.com/StevenBlack/hosts/blob/master/extensions/social/update.json), and let me know if this is OK?

Thanks!

**Comment by Sinfonietta** [comment]
👍 LGTM
