### ISSUE TITLE
a little more porn to block

### ISSUE THREAD

**Issue by Danilopereira82** [Sinfonietta/hostfiles#70]
# i learned how to sort using vim
185.136.162.5 # god please block this one, my eyes are burning
2adultflashgames.com
adult-sex-games.com
ayouou.com
bestlistofporn.com
bestlovesexdoll.com
bestsexgamesonline.com
bigtitstube.xxx
boobgoddess.com
boobieblog.com
br.skokka.com
bustyshots.com
chestmeat.com
collegeporn.net
diskacompanhantes.com.br
eggporncomics.com
floppy-tits.com
gamcore.com
hentaibros.com
hentaiknight.com
hentaisea.com
hentaiwire.com
hornygamer.com
iwantporn.net
joylovedolls.com
kikdolls.com
linkrosa.com.br
loversdolls.com
miohentai.com
mysexgames.com
nevadaescorts.us
nichepornsites.com
nime.freehentaistream.com
nubileporn.net
oksexdoll.com
paysitesreviews.net
pleasure-seeker.com
pornfrost.com
porngames.com
pornsites.xxx
primecurves.com
sakuracircle.animeholics.org
scandalplanet.com
sexdollfetish.store
sexdollmarts.com
sexgames.cc
sexyfuckgames.com
sharkyporn.com
sihteeriopisto.co
skokka.com
splove.com.br
theporndude.com
thepornmap.com
titsintops.com
titsintopstube.com
tittyvoyeur.com
topescortbabes.com
urdolls.com
wetpussygames.com
xpornolist.com
xxxgames.biz
yourdoll.com

**Comment by Sinfonietta** [comment]
Thank you @Danilopereira82, these have been added in commit 0d64c4ad5f4b.

**Comment by spirillen** [comment]
@Danilopereira82 what is it about the IP `185.136.162.5`?

**Comment by erosguide** [comment]
Left to mention the most famous site of whores from São Paulo Brazil 
www.hottescorts.com.br
