### ISSUE TITLE
porn to block ( :< not much, but honest work )

### ISSUE THREAD

**Issue by Danilopereira82** [Sinfonietta/hostfiles#71]
server9.mangovideo.pw
surf-communication.com

**Comment by Sinfonietta** [comment]
Thanks @Danilopereira82, good find.  These are added to the list.

**Comment by spirillen** [comment]
Hi @Sinfonietta 

Have not checked if these does exist in your list, but the `server9.mangovideo.pw` made me dig for alternatives, and found these

```
server1.mangovideo.pw
server2.mangovideo.pw

```

Self note: https://gitlab.com/my-privacy-dns/matrix/matrix/issues/1500
