### ISSUE TITLE
block porn | edited

### ISSUE THREAD

**Issue by Danilopereira82** [Sinfonietta/hostfiles#74]
https://smutba.se/
https://drive.google.com/drive/folders/0BzXJEA3VM5iYUW4yYzhVZHN4RFU
https://e926.net/ ## e621.net is already blocked, this site is suposed to be the sfw version but still has a lot of fetish and sexy stuff, i think would be better to block
https://sexchannelhd.us/media/
https://static1.e621.net/ ## e621 is already in the list but its server is not, so its still possible to access the pornography

**Comment by Sinfonietta** [comment]
Thank you.  I have added smutba.se.  The others are either offline already, or aren't immediately offensive.  We can't block `drive.google.com`....

**Comment by Danilopereira82** [comment]
damn :T
can't just block the entire address

**Comment by Sinfonietta** [comment]
@Danilopereira82 ya... hosts files work with the domain or subdomain only, not the rest of the address.

**Comment by spirillen** [comment]
@Danilopereira82 I know [EasyList](https://github.com/easylist/easylist) is doing something into some degree of porn blocking by url
