### ISSUE TITLE
block more Hentai

### ISSUE THREAD

**Issue by Danilopereira82** [Sinfonietta/hostfiles#77]
atfbooru.ninja
booru.allthefallen.moe
danbooru.donmai.us
sexacartoon.com
thehentaiworld.com
hentaiporns.net
megapornpics.com
nerdporn.sexy
toons.freesexycomics.com
link4game.com
fucknstein.com
xxgasm.com
iluvtoons.com
berufsbildungsbericht.info
freehentaidb.com
aspniinn.com

**Comment by Sinfonietta** [comment]
Thanks @Danilopereira82 added!
