### ISSUE TITLE
block moar plis

### ISSUE THREAD

**Issue by ghost** [Sinfonietta/hostfiles#80]
sub-lewd.tumblr.com
hentaibeast.com
hcomicbook.com
ibsearch.xxx
ulmf.org
hentaifortune.tv
sxshentai.com
h-moe.com
myanimeron.net

**Comment by spirillen** [comment]
> ulmf.org

I can't find any NSFW  on this board, could you post a link/screenshot?

_Self note:_ https://gitlab.com/my-privacy-dns/matrix/matrix/commit/b87ce9ed40bb4a380e995fb7da7d558cf6f86086
