### ISSUE TITLE
e621 is back on the hood

### ISSUE THREAD

**Issue by ghost** [Sinfonietta/hostfiles#81]
https://beta.e621.net/

**Comment by Sinfonietta** [comment]
Not seeing porn here, @Danilopereira82?

**Comment by Danilopereira82** [comment]
> Not seeing porn here, @Danilopereira82?

https://beta.e621.net/posts/204
you are just not looking hard enough

**Comment by spirillen** [comment]
Sins the hosts at the writing moment is down you can see a screenshot in my post https://github.com/spirillen/pornhosts/issues/15

**Comment by Danilopereira82** [comment]
they are not using the beta site anymore
