### ISSUE TITLE
Block more porn | need analize 

### ISSUE THREAD

**Issue by ghost** [Sinfonietta/hostfiles#82]
//! can you delete the other issues please?
they are already closed

*number* means that the sites seems to be somehow connected, even if they are in different categories  

[Porn] it means the site has pornography or lewd stuff enough to disturb a working place or someone into NoFap

[Maybe Porn] it means that i am not 100% sure, the site has some lewd stuff, but don't seem to be pornography or the intention of the site doesn't seem to be about porn

can you believe i got this all from just 2 pages of https://booru.org/top ?

//!

[Porn]
rule34c.paheal.net
rule34hentai.net
rule34video.com
rule34tube.net
drunkenpumken.booru.org
footfetishbooru.booru.org
illusioncards.booru.org *1*
icis.booru.org
vidyart2.booru.org
b00b3d.booru.org
clop.booru.org
closeup.booru.org
bjd.booru.org
sonicfeet.booru.org
collection.booru.org
deviants-despository.booru.org
stevenuniverse.booru.org //! doesn't seems to be porn at first, but in the later pages its possible to find a lot //!
id.booru.org
webarebears.booru.org
yaoibooru.booru.org
zoo.booru.org //! this site is 50/50, i'm not sure if it should be blocked //!
blacked.booru.org
pokeymans.booru.org
crewbooru.booru.org
wolf.booru.org
very.booru.org
dp.booru.org
darkeh.booru.org
haniho.booru.org
lisathepainful.booru.org //! has some porn stuff, should it be blocked? //!
consoletan.booru.org
randomarchive.booru.org
lonehowl.booru.org
pai.booru.org
sg.booru.org //! has some porn stuff, but most of the site are just full of random things //!
qoh.booru.org
sprinkles.booru.org
abm.booru.org //! 50/50 //!
buffies.booru.org
galaxy.booru.org
aa2share.booru.org *1*
penis.booru.org
jds.booru.org
randomarchive3.booru.org
bigmen.booru.org
fuck.booru.org
elderscrollsbooru.booru.org
fafu.booru.org
hentaiecchi.booru.org
ourobooru.booru.org //! 50/50 too, has some porn, but most of it are arts //!
gasexplosion.booru.org
mof.booru.org
naf.booru.org
ryusei.booru.org //! at first don't seem to have porn, but in latter pages has a lot //!
jamesab-art.booru.org
jaemi.booru.org
steelvaginas.booru.org
sof.booru.org
arianisus.booru.org
lisatheartful.booru.org
under.booru.org
g-goes-wild.booru.org //! like... you just need to see the front page to confirm //!
bboy.booru.org //! at first looks like it only have pictures of thots, but its full of hentai stuff //!
stud.booru.org //! horse sex //!
zg.booru.org
quest.booru.org
oporal.booru.org
randomgalleryvault.booru.org
streep.booru.org
cutie.booru.org
fs.booru.org
kyra.booru.org
snyde.booru.org
omni.booru.org
su.booru.org
theride.booru.org
christianmar762userxbooru.booru.org
bbw.booru.org
pokephilia.booru.org
hell.booru.org
sekaiju.booru.org
touhoufeet.booru.org
woh.booru.org
100oj.booru.org
nsfwhomestuck.booru.org
digitalmonster.booru.org
madpicz.booru.org
3d.booru.org
smtg.booru.org

[Maybe Porn]
allgirl.booru.org
icscn.booru.org *1*
aa2cc.booru.org *1*
daitrombe.booru.org
card.booru.org
trashdump.booru.org
vocalo.booru.org //! has big boob 🤤, but i'm not sure if it should be blocked //!
channel-tan.booru.org //! weird... the site is not working well for me, need some analyze //! 
proton.booru.org
teamfortress.booru.org
undertale.booru.org
rooru.booru.org
celebarch.booru.org //! movie stuff? //!
cutebooru.booru.org
ikkitousen.booru.org

[Scamm !?]
wetmeets.com

**Comment by spirillen** [comment]
> can you believe i got this all from just 2 pages 

Even if you have said 1 page :smile: :laughing:

**Comment by spirillen** [comment]
PS @Danilopereira82 the https://github.com/Import-External-Sources/pornhosts from https://github.com/Clefspeare13/pornhosts is up and running after @funilrys fixed the issues with https://github.com/funilrys/PyFunceble/tree/dev

So if you submit you lists to https://github.com/Import-External-Sources/pornhosts/blob/master/submit_here/hosts.txt (But only chose you are certain on) and then creates a PR I'll put them only within a couple of hours

**Comment by spirillen** [comment]
I can't find any adult related content on `zoo.booru.org`

**Comment by spirillen** [comment]
What I can find at `sg.booru.org` seems all SFW, couldn't find anything that even a US new religious female could complain about

**Comment by Danilopereira82** [comment]
> I can't find any adult related content on `zoo.booru.org`
even in the first page
https://zoo.booru.org/index.php?page=post&s=view&id=21172
https://zoo.booru.org/index.php?page=post&s=view&id=21171

**Comment by Danilopereira82** [comment]
> What I can find at `sg.booru.org` seems all SFW, couldn't find anything that even a US new religious female could complain about

https://sg.booru.org/index.php?page=post&s=view&id=8885
https://sg.booru.org/index.php?page=post&s=view&id=8870
https://sg.booru.org/index.php?page=post&s=view&id=8837
https://sg.booru.org/index.php?page=post&s=view&id=8829
https://sg.booru.org/index.php?page=post&s=view&id=8818
https://sg.booru.org/index.php?page=post&s=view&id=8822

**Comment by Danilopereira82** [comment]
> > can you believe i got this all from just 2 pages
> 
> Even if you have said 1 page smile laughing

i mean
https://booru.org/top

**Comment by spirillen** [comment]
Ok
```
https://sg.booru.org/index.php?page=post&s=view&id=8829
https://sg.booru.org/index.php?page=post&s=view&id=8822

``` 
These one could maybe if if if if, but njaaa, not in my book, that's not enough

And have added

`zoo.booru.org`

But you are right, do these belongs to such a list because of a few images??

**Comment by spirillen** [comment]
LOL I'm not even trying to click that yes/no :rofl:  and all backgrounds is stolen from metart and femjoy :smile:

**Comment by Danilopereira82** [comment]
> zoo.booru.org

https://zoo.booru.org/index.php?page=post&s=list&tags=anal

**Comment by spirillen** [comment]
> > zoo.booru.org
> 
> https://zoo.booru.org/index.php?page=post&s=list&tags=anal

Is already added.... https://github.com/Import-External-Sources/pornhosts/issues/114

**Comment by Danilopereira82** [comment]
> > > zoo.booru.org
> > 
> > 
> > https://zoo.booru.org/index.php?page=post&s=list&tags=anal
> 
> Is already added.... [Import-External-Sources/pornhosts#114](https://github.com/Import-External-Sources/pornhosts/issues/114)
> 
> We are only waiting for the [build](https://travis-ci.com/Import-External-Sources/pornhosts/builds) to complete smile

man you know any way to get links from html pages?
its boring to be clicking page by page

**Comment by spirillen** [comment]
That depends....

What exactly is it you would like to do?

**Comment by Danilopereira82** [comment]
> That depends....
> 
> What exactly is it you would like to do?

extract links from sites like this

**Comment by spirillen** [comment]
What browser are you using? in firefox you can ex. use [uBlock Origin](https://github.com/gorhill/uBlock) and open the "Logger"

That will give you a window like this

![image](https://user-images.githubusercontent.com/44526987/73489808-88b12200-43ab-11ea-852b-f88e78bf1373.png)

You can export that in four ways

1. 
<details><summary>Logger output</summary>

```
+2
www.mypdns.org
1
image
https://www.mypdns.org/chrome/common/trac.ico
```
```
+2
www.mypdns.org
1
css
https://www.mypdns.org/chrome/tags/css/tractags.css
```
```
+2
www.mypdns.org
1
css
https://www.mypdns.org/chrome/common/css/code.css
```
```
+2
www.mypdns.org
1
image
https://www.mypdns.org/chrome/common/trac_logo_mini.png
```
```
+2
www.mypdns.org
3
image
https://my-privacy-dns.gitlab.io/matrix/matrix/logo.png
```
```
+2
www.mypdns.org
1
script
https://www.mypdns.org/chrome/common/js/wiki.js
```
```
+2
www.mypdns.org
1
script
https://www.mypdns.org/chrome/common/js/folding.js
```
```
+2
www.mypdns.org
1
script
https://www.mypdns.org/chrome/common/js/search.js
```
```
+2
www.mypdns.org
1
script
https://www.mypdns.org/chrome/common/js/trac.js
```
```
+2
www.mypdns.org
1
script
https://www.mypdns.org/chrome/common/js/babel.js
```
```
+2
www.mypdns.org
1
script
https://www.mypdns.org/chrome/common/js/jquery.js
```
```
+2
www.mypdns.org
1
css
https://www.mypdns.org/chrome/common/css/wiki.css
```
```
+2
www.mypdns.org
1
css
https://www.mypdns.org/chrome/common/css/trac.css
```
```
+0
whitelisted
++
www.mypdns.org
1
doc
https://www.mypdns.org/
```
```
+0
https://www.mypdns.org/
```
```
+0
mypdns.org
1
doc
http://mypdns.org/
```
```
+0
http://mypdns.org/
```
</details>


1. 
<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +2 |  |  | `www.mypdns.org` | 1 | image | `https://www.mypdns.org/chrome/common/trac.ico` |
| +2 |  |  | `www.mypdns.org` | 1 | css | `https://www.mypdns.org/chrome/tags/css/tractags.css` |
| +2 |  |  | `www.mypdns.org` | 1 | css | `https://www.mypdns.org/chrome/common/css/code.css` |
| +2 |  |  | `www.mypdns.org` | 1 | image | `https://www.mypdns.org/chrome/common/trac_logo_mini.png` |
| +2 |  |  | `www.mypdns.org` | 3 | image | `https://my-privacy-dns.gitlab.io/matrix/matrix/logo.png` |
| +2 |  |  | `www.mypdns.org` | 1 | script | `https://www.mypdns.org/chrome/common/js/wiki.js` |
| +2 |  |  | `www.mypdns.org` | 1 | script | `https://www.mypdns.org/chrome/common/js/folding.js` |
| +2 |  |  | `www.mypdns.org` | 1 | script | `https://www.mypdns.org/chrome/common/js/search.js` |
| +2 |  |  | `www.mypdns.org` | 1 | script | `https://www.mypdns.org/chrome/common/js/trac.js` |
| +2 |  |  | `www.mypdns.org` | 1 | script | `https://www.mypdns.org/chrome/common/js/babel.js` |
| +2 |  |  | `www.mypdns.org` | 1 | script | `https://www.mypdns.org/chrome/common/js/jquery.js` |
| +2 |  |  | `www.mypdns.org` | 1 | css | `https://www.mypdns.org/chrome/common/css/wiki.css` |
| +2 |  |  | `www.mypdns.org` | 1 | css | `https://www.mypdns.org/chrome/common/css/trac.css` |
| +0 | whitelisted | ++ | `www.mypdns.org` | 1 | doc | `https://www.mypdns.org/` |
| +0 |  |  | mypdns.org | 1 | doc | `http://mypdns.org/` |
</details>

3. 
+2			www.mypdns.org	1	image	https://www.mypdns.org/chrome/common/trac.ico
+2			www.mypdns.org	1	css	https://www.mypdns.org/chrome/tags/css/tractags.css
+2			www.mypdns.org	1	css	https://www.mypdns.org/chrome/common/css/code.css
+2			www.mypdns.org	1	image	https://www.mypdns.org/chrome/common/trac_logo_mini.png
+2			www.mypdns.org	3	image	https://my-privacy-dns.gitlab.io/matrix/matrix/logo.png
+2			www.mypdns.org	1	script	https://www.mypdns.org/chrome/common/js/wiki.js
+2			www.mypdns.org	1	script	https://www.mypdns.org/chrome/common/js/folding.js
+2			www.mypdns.org	1	script	https://www.mypdns.org/chrome/common/js/search.js
+2			www.mypdns.org	1	script	https://www.mypdns.org/chrome/common/js/trac.js
+2			www.mypdns.org	1	script	https://www.mypdns.org/chrome/common/js/babel.js
+2			www.mypdns.org	1	script	https://www.mypdns.org/chrome/common/js/jquery.js
+2			www.mypdns.org	1	css	https://www.mypdns.org/chrome/common/css/wiki.css
+2			www.mypdns.org	1	css	https://www.mypdns.org/chrome/common/css/trac.css
+0	whitelisted	++	www.mypdns.org	1	doc	https://www.mypdns.org/
+0	https://www.mypdns.org/
+0			mypdns.org	1	doc	http://mypdns.org/
+0	http://mypdns.org/

4.
+2
www.mypdns.org
1
image
https://www.mypdns.org/chrome/common/trac.ico

+2
www.mypdns.org
1
css
https://www.mypdns.org/chrome/tags/css/tractags.css

+2
www.mypdns.org
1
css
https://www.mypdns.org/chrome/common/css/code.css

+2
www.mypdns.org
1
image
https://www.mypdns.org/chrome/common/trac_logo_mini.png

+2
www.mypdns.org
3
image
https://my-privacy-dns.gitlab.io/matrix/matrix/logo.png

+2
www.mypdns.org
1
script
https://www.mypdns.org/chrome/common/js/wiki.js

+2
www.mypdns.org
1
script
https://www.mypdns.org/chrome/common/js/folding.js

+2
www.mypdns.org
1
script
https://www.mypdns.org/chrome/common/js/search.js

+2
www.mypdns.org
1
script
https://www.mypdns.org/chrome/common/js/trac.js

+2
www.mypdns.org
1
script
https://www.mypdns.org/chrome/common/js/babel.js

+2
www.mypdns.org
1
script
https://www.mypdns.org/chrome/common/js/jquery.js

+2
www.mypdns.org
1
css
https://www.mypdns.org/chrome/common/css/wiki.css

+2
www.mypdns.org
1
css
https://www.mypdns.org/chrome/common/css/trac.css

+0
whitelisted
++
www.mypdns.org
1
doc
https://www.mypdns.org/

+0
https://www.mypdns.org/

+0
mypdns.org
1
doc
http://mypdns.org/

+0
http://mypdns.org/


That is almost the easiest way in a graphical way

but there is also a bash (Linux) way of doing this, but that would requires a bit more coding to extract
