### ISSUE TITLE
was this blocked already?

### ISSUE THREAD

**Issue by Danilopereira82** [Sinfonietta/hostfiles#84]
http://www.aerisdies.com/

**Comment by spirillen** [comment]
if you are on a linux box you can test it by this "simple" command in your promt

`wget -qO- 'https://raw.githubusercontent.com/Sinfonietta/hostfiles/master/pornography-hosts' | grep 'aerisdies.com'`

Or do the search within the browser https://raw.githubusercontent.com/Sinfonietta/hostfiles/master/pornography-hosts ``ctrl + f``

But I couldn't find it :smiling_imp:

**Comment by Sinfonietta** [comment]
Thanks @Danilopereira82 this is added in commit a60e508aa612af1a51cbeed5197454351f2aaa3a
