### ISSUE TITLE
instagram subdomains

### ISSUE THREAD

**Issue by me-ch** [Sinfonietta/hostfiles#89]
Some of these are pre sorted, these are subdomains of cdninstagram.com queried by third party instagram viewing websites. There are just too many instagram viewers out there and every day a new one is created. So i retrieved these from: https://securitytrails.com/list/apex_domain/cdninstagram.
I encourage any contributor that wants to get subdomains from a general domain to use this website in order to cover as much ground as possible. Btw thanks for starting this project.

0.0.0.0 a.ns.cdninstagram.com
0.0.0.0 b.ns.cdninstagram.com
0.0.0.0 c.ns.cdninstagram.com	
0.0.0.0 creative.cdninstagram.com
0.0.0.0 d.ns.cdninstagram.com
0.0.0.0 dragon.cdninstagram.com
0.0.0.0 external.cdninstagram.com
0.0.0.0 openvpn.cdninstagram.com
0.0.0.0 platform.cdninstagram.com
0.0.0.0 scontent-a-ams.cdninstagram.com
0.0.0.0 scontent-a-amt.cdninstagram.com
0.0.0.0 scontent-a-arn.cdninstagram.com
0.0.0.0 scontent-a-atl.cdninstagram.com
0.0.0.0 scontent-a-bog.cdninstagram.com
0.0.0.0 scontent-a-bru.cdninstagram.com
0.0.0.0 scontent-a-cdg.cdninstagram.com
0.0.0.0 scontent-a-dfw.cdninstagram.com
0.0.0.0 scontent-a-eze.cdninstagram.com
0.0.0.0 scontent-a-frt.cdninstagram.com
0.0.0.0 scontent-a-frx.cdninstagram.com
0.0.0.0 scontent-a-gru.cdninstagram.com
0.0.0.0 scontent-a-hkg.cdninstagram.com
0.0.0.0 scontent-a-iad.cdninstagram.com
0.0.0.0 scontent-a-kut.cdninstagram.com
0.0.0.0 scontent-a-lax.cdninstagram.com
0.0.0.0 scontent-a-lga.cdninstagram.com
0.0.0.0 scontent-a-lht.cdninstagram.com
0.0.0.0 scontent-a-mad.cdninstagram.com
0.0.0.0 scontent-a-mia.cdninstagram.com
0.0.0.0 scontent-a-mrs.cdninstagram.com
0.0.0.0 scontent-a-mxp.cdninstagram.com
0.0.0.0 scontent-a-nrt.cdninstagram.com
0.0.0.0 scontent-a-ort.cdninstagram.com
0.0.0.0 scontent-a-otp.cdninstagram.com
0.0.0.0 scontent-a-scl.cdninstagram.com
0.0.0.0 scontent-a-sea.cdninstagram.com
0.0.0.0 scontent-a-sin.cdninstagram.com
0.0.0.0 scontent-a-sjc.cdninstagram.com
0.0.0.0 scontent-a-sof.cdninstagram.com
0.0.0.0 scontent-a-syd.cdninstagram.com
0.0.0.0 scontent-a-tpe.cdninstagram.com
0.0.0.0 scontent-a-vie.cdninstagram.com
0.0.0.0 scontent-a-waw.cdninstagram.com
0.0.0.0 scontent-a-yyz.cdninstagram.com
0.0.0.0 scontent-a.cdninstagram.com
0.0.0.0 scontent-ams.cdninstagram.com
0.0.0.0 scontent-ams3-1.cdninstagram.com
0.0.0.0 scontent-ams4-1.cdninstagram.com
0.0.0.0 scontent-amt2-1.cdninstagram.com
0.0.0.0 scontent-arn.cdninstagram.com
0.0.0.0 scontent-arn2-1.cdninstagram.com
0.0.0.0 scontent-arn2-2.cdninstagram.com
0.0.0.0 scontent-atl.cdninstagram.com
0.0.0.0 scontent-atl3-1.cdninstagram.com
0.0.0.0 scontent-b-ams.cdninstagram.com
0.0.0.0 scontent-b-amt.cdninstagram.com
0.0.0.0 scontent-b-arn.cdninstagram.com
0.0.0.0 scontent-b-atl.cdninstagram.com
0.0.0.0 scontent-b-bog.cdninstagram.com
0.0.0.0 scontent-b-bru.cdninstagram.com
0.0.0.0 scontent-b-cdg.cdninstagram.com
0.0.0.0 scontent-b-dfw.cdninstagram.com
0.0.0.0 scontent-b-eze.cdninstagram.com
0.0.0.0 scontent-b-frt.cdninstagram.com
0.0.0.0 scontent-b-frx.cdninstagram.com
0.0.0.0 scontent-b-gru.cdninstagram.com
0.0.0.0 scontent-b-hkg.cdninstagram.com
0.0.0.0 scontent-b-iad.cdninstagram.com
0.0.0.0 scontent-b-icn.cdninstagram.com
0.0.0.0 scontent-b-kut.cdninstagram.com
0.0.0.0 scontent-b-lax.cdninstagram.com
0.0.0.0 scontent-b-lga.cdninstagram.com
0.0.0.0 scontent-b-lhr.cdninstagram.com
0.0.0.0 scontent-b-lht.cdninstagram.com
0.0.0.0 scontent-b-mad.cdninstagram.com
0.0.0.0 scontent-b-mia.cdninstagram.com
0.0.0.0 scontent-b-mrs.cdninstagram.com
0.0.0.0 scontent-b-mxp.cdninstagram.com
0.0.0.0 scontent-b-nrt.cdninstagram.com
0.0.0.0 scontent-b-ord.cdninstagram.com
0.0.0.0 scontent-b-ort.cdninstagram.com
0.0.0.0 scontent-b-otp.cdninstagram.com
0.0.0.0 scontent-b-pao.cdninstagram.com
0.0.0.0 scontent-b-scl.cdninstagram.com
0.0.0.0 scontent-b-scl.cdninstagram.com
0.0.0.0 scontent-b-sea.cdninstagram.com
0.0.0.0 scontent-b-sin.cdninstagram.com
0.0.0.0 scontent-b-sjc.cdninstagram.com
0.0.0.0 scontent-b-sof.cdninstagram.com
0.0.0.0 scontent-b-syd.cdninstagram.com
0.0.0.0 scontent-b-tpe.cdninstagram.com
0.0.0.0 scontent-b-vie.cdninstagram.com
0.0.0.0 scontent-b-waw.cdninstagram.com
0.0.0.0 scontent-b-yyz.cdninstagram.com
0.0.0.0 scontent-b.cdninstagram.com
0.0.0.0 scontent-ber1-1.cdninstagram.com
0.0.0.0 scontent-bog1-1.cdninstagram.com
0.0.0.0 scontent-bom1-1.cdninstagram.com
0.0.0.0 scontent-bos3-1.cdninstagram.com
0.0.0.0 scontent-bru.cdninstagram.com
0.0.0.0 scontent-bru2-1.cdninstagram.com
0.0.0.0 scontent-cai1-1.cdninstagram.com
0.0.0.0 scontent-cdg.cdninstagram.com
0.0.0.0 scontent-cdg2-1.cdninstagram.com
0.0.0.0 scontent-cdt.cdninstagram.com
0.0.0.0 scontent-cdt1-1.cdninstagram.com
0.0.0.0 scontent-cgk.cdninstagram.com
0.0.0.0 scontent-cgk1-1.cdninstagram.com
0.0.0.0 scontent-cph2-1.cdninstagram.com
0.0.0.0 scontent-del1-1.cdninstagram.com
0.0.0.0 scontent-den4-1.cdninstagram.com
0.0.0.0 scontent-dft4-1.cdninstagram.com
0.0.0.0 scontent-dft4-2.cdninstagram.com
0.0.0.0 scontent-dft4-3.cdninstagram.com
0.0.0.0 scontent-dfw.cdninstagram.com
0.0.0.0 scontent-dfw1-1.cdninstagram.com
0.0.0.0 scontent-dfw5-1.cdninstagram.com
0.0.0.0 scontent-dfw5-2.cdninstagram.com
0.0.0.0 scontent-dub4-1.cdninstagram.com
0.0.0.0 scontent-dus.cdninstagram.com
0.0.0.0 scontent-dus1-1.cdninstagram.com
0.0.0.0 scontent-eze1-1.cdninstagram.com
0.0.0.0 scontent-fco1-1.cdninstagram.com
0.0.0.0 scontent-fml1-1.cdninstagram.com
0.0.0.0 scontent-fml2-1.cdninstagram.com
0.0.0.0 scontent-for1-1.cdninstagram.com
0.0.0.0 scontent-fra3-1.cdninstagram.com
0.0.0.0 scontent-frt.cdninstagram.com
0.0.0.0 scontent-frt3-1.cdninstagram.com
0.0.0.0 scontent-frt3-2.cdninstagram.com
0.0.0.0 scontent-frx.cdninstagram.com	
0.0.0.0 scontent-frx5-1.cdninstagram.com
0.0.0.0 scontent-gig2-1.cdninstagram.com
0.0.0.0 scontent-gmp1-1.cdninstagram.com
0.0.0.0 scontent-gru.cdninstagram.com
0.0.0.0 scontent-gru1-1.cdninstagram.com
0.0.0.0 scontent-gru2-1.cdninstagram.com
0.0.0.0 scontent-gru2-2.cdninstagram.com
0.0.0.0 scontent-ham3-1.cdninstagram.com
0.0.0.0 scontent-hbe1-1.cdninstagram.com
0.0.0.0 scontent-hel2-1.cdninstagram.com
0.0.0.0 scontent-hkg.cdninstagram.com
0.0.0.0 scontent-hkg3-1.cdninstagram.com
0.0.0.0 scontent-hkg3-2.cdninstagram.com
0.0.0.0 scontent-hkt1-1.cdninstagram.com
0.0.0.0 scontent-iad.cdninstagram.com
0.0.0.0 scontent-iad3-1.cdninstagram.com
0.0.0.0 scontent-icn1-1.cdninstagram.com
0.0.0.0 scontent-itm1-1.cdninstagram.com
0.0.0.0 scontent-jnb1-1.cdninstagram.com
0.0.0.0 scontent-kul1-1.cdninstagram.com
0.0.0.0 scontent-kut2-1.cdninstagram.com
0.0.0.0 scontent-kut2-2.cdninstagram.com
0.0.0.0 scontent-lax.cdninstagram.com
0.0.0.0 scontent-lax3-1.cdninstagram.com
0.0.0.0 scontent-lax3-2.cdninstagram.com
0.0.0.0 scontent-lga.cdninstagram.com
0.0.0.0 scontent-lga3-1.cdninstagram.com
0.0.0.0 scontent-lhr.cdninstagram.com
0.0.0.0 scontent-lhr3-1.cdninstagram.com
0.0.0.0 scontent-lhr8-1.cdninstagram.com
0.0.0.0 scontent-lht6-1.cdninstagram.com
0.0.0.0 scontent-lim1-1.cdninstagram.com
0.0.0.0 scontent-lis1-1.cdninstagram.com
0.0.0.0 scontent-maa2-1.cdninstagram.com
0.0.0.0 scontent-maa2-2.cdninstagram.com
0.0.0.0 scontent-mad.cdninstagram.com
0.0.0.0 scontent-mad1-1.cdninstagram.com
0.0.0.0 scontent-mba1-1.cdninstagram.com
0.0.0.0 scontent-mia.cdninstagram.com
0.0.0.0 scontent-mia1-1.cdninstagram.com
0.0.0.0 scontent-mia1-2.cdninstagram.com
0.0.0.0 scontent-mia3-1.cdninstagram.com
0.0.0.0 scontent-mia3-2.cdninstagram.com
0.0.0.0 scontent-mrs.cdninstagram.com
0.0.0.0 scontent-mrs1-1.cdninstagram.com
0.0.0.0 scontent-mrs2-1.cdninstagram.com
0.0.0.0 scontent-mrs2-2.cdninstagram.com
0.0.0.0 scontent-msp1-1.cdninstagram.com
0.0.0.0 scontent-mxp.cdninstagram.com
0.0.0.0 scontent-mxp1-1.cdninstagram.com
0.0.0.0 scontent-nrt.cdninstagram.com
0.0.0.0 scontent-nrt1-1.cdninstagram.com
0.0.0.0 scontent-ord.cdninstagram.com
0.0.0.0 scontent-ord1-1.cdninstagram.com
0.0.0.0 scontent-ort2-1.cdninstagram.com
0.0.0.0 scontent-ort2-2.cdninstagram.com
0.0.0.0 scontent-otp1-1.cdninstagram.com
0.0.0.0 scontent-prg1-1.cdninstagram.com
0.0.0.0 scontent-qro1-1.cdninstagram.com
0.0.0.0 scontent-scl1-1.cdninstagram.com
0.0.0.0 scontent-scl2-1.cdninstagram.com
0.0.0.0 scontent-sea.cdninstagram.com
0.0.0.0 scontent-sea1-1.cdninstagram.com
0.0.0.0 scontent-sin.cdninstagram.com
0.0.0.0 scontent-sin2-1.cdninstagram.com
0.0.0.0 scontent-sin2-2.cdninstagram.com
0.0.0.0 scontent-sin6-1.cdninstagram.com
0.0.0.0 scontent-sin6-2.cdninstagram.com
0.0.0.0 scontent-sin9-1.cdninstagram.com
0.0.0.0 scontent-sit4-1.cdninstagram.com
0.0.0.0 scontent-sjc.cdninstagram.com
0.0.0.0 scontent-sjc2-1.cdninstagram.com
0.0.0.0 scontent-sjc3-1.cdninstagram.com
0.0.0.0 scontent-sju1-1.cdninstagram.com
0.0.0.0 scontent-sof.cdninstagram.com
0.0.0.0 scontent-sof1-1.cdninstagram.com
0.0.0.0 scontent-ssn1-1.cdninstagram.com
0.0.0.0 scontent-syd2-1.cdninstagram.com
0.0.0.0 scontent-tpe.cdninstagram.com
0.0.0.0 scontent-tpe1-1.cdninstagram.com
0.0.0.0 scontent-vie.cdninstagram.com
0.0.0.0 scontent-vie1-1.cdninstagram.com
0.0.0.0 scontent-waw1-1.cdninstagram.com
0.0.0.0 scontent-xsp.cdninstagram.com
0.0.0.0 scontent-xsp1-1.cdninstagram.com
0.0.0.0 scontent-xsp1-2.cdninstagram.com
0.0.0.0 scontent-yyz1-1.cdninstagram.com
0.0.0.0 scontent-zrh1-1.cdninstagram.com
0.0.0.0 scontent.cdninstagram.com
0.0.0.0 static.cdninstagram.com
0.0.0.0 video-nrt1-1.cdninstagram.com
0.0.0.0 video-ort2-1.cdninstagram.com
0.0.0.0 video-ort2-2.cdninstagram.com
0.0.0.0 video.cdninstagram.com
0.0.0.0 www.cdninstagram.com
0.0.0.0 z-p15-scontent-bru2-1.cdninstagram.com
0.0.0.0 z-p15-scontent-cdg2-1.cdninstagram.com
0.0.0.0 z-p15-scontent-cdt1-1.cdninstagram.com
0.0.0.0 z-p15-scontent-lhr3-1.cdninstagram.com
0.0.0.0 z-p15-scontent-lht6-1.cdninstagram.com
0.0.0.0 z-p15-scontent.cdninstagram.com
0.0.0.0 z-p4-scontent-ams3-1.cdninstagram.com
0.0.0.0 z-p4-scontent-ams4-1.cdninstagram.com
0.0.0.0 z-p4-scontent-amt2-1.cdninstagram.com
0.0.0.0 z-p4-scontent-arn2-1.cdninstagram.com
0.0.0.0 z-p4-scontent-arn2-2.cdninstagram.com
0.0.0.0 z-p4-scontent-bru2-1.cdninstagram.com
0.0.0.0 z-p4-scontent-cdg2-1.cdninstagram.com
0.0.0.0 z-p4-scontent-cdt1-1.cdninstagram.com
0.0.0.0 z-p4-scontent-dfw5-1.cdninstagram.com
0.0.0.0 z-p4-scontent-frt3-1.cdninstagram.com
0.0.0.0 z-p4-scontent-frt3-2.cdninstagram.com
0.0.0.0 z-p4-scontent-frx5-1.cdninstagram.com
0.0.0.0 z-p4-scontent-lax3-1.cdninstagram.com
0.0.0.0 z-p4-scontent-lga3-1.cdninstagram.com
0.0.0.0 z-p4-scontent-lhr3-1.cdninstagram.com
0.0.0.0 z-p4-scontent-lht6-1.cdninstagram.com
0.0.0.0 z-p4-scontent-mrs1-1.cdninstagram.com
0.0.0.0 z-p4-scontent-mxp1-1.cdninstagram.com
0.0.0.0 z-p4-scontent-otp1-1.cdninstagram.com
0.0.0.0 z-p4-scontent-waw1-1.cdninstagram.com
0.0.0.0 z-p4-scontent.cdninstagram.com
0.0.0.0 z-p42-scontent-ams3-1.cdninstagram.com
0.0.0.0 z-p42-scontent-amt2-1.cdninstagram.com
0.0.0.0 z-p42-scontent-arn2-1.cdninstagram.com
0.0.0.0 z-p42-scontent-arn2-2.cdninstagram.com
0.0.0.0 z-p42-scontent-atl3-1.cdninstagram.com
0.0.0.0 z-p42-scontent-ber1-1.cdninstagram.com
0.0.0.0 z-p42-scontent-bom1-1.cdninstagram.com
0.0.0.0 z-p42-scontent-bom1-2.cdninstagram.com
0.0.0.0 z-p42-scontent-bru2-1.cdninstagram.com
0.0.0.0 z-p42-scontent-cdg2-1.cdninstagram.com
0.0.0.0 z-p42-scontent-cdt1-1.cdninstagram.com
0.0.0.0 z-p42-scontent-dfw5-1.cdninstagram.com
0.0.0.0 z-p42-scontent-dfw5-2.cdninstagram.com
0.0.0.0 z-p42-scontent-dub4-1.cdninstagram.com
0.0.0.0 z-p42-scontent-dus1-1.cdninstagram.com
0.0.0.0 z-p42-scontent-frt3-1.cdninstagram.com
0.0.0.0 z-p42-scontent-frt3-2.cdninstagram.com
0.0.0.0 z-p42-scontent-frx5-1.cdninstagram.com
0.0.0.0 z-p42-scontent-hbe1-1.cdninstagram.com
0.0.0.0 z-p42-scontent-hkg3-1.cdninstagram.com
0.0.0.0 z-p42-scontent-iad3-1.cdninstagram.com
0.0.0.0 z-p42-scontent-icn1-1.cdninstagram.com
0.0.0.0 z-p42-scontent-jnb1-1.cdninstagram.com
0.0.0.0 z-p42-scontent-lax3-1.cdninstagram.com
0.0.0.0 z-p42-scontent-lax3-2.cdninstagram.com
0.0.0.0 z-p42-scontent-lga3-1.cdninstagram.com
0.0.0.0 z-p42-scontent-lhr3-1.cdninstagram.com
0.0.0.0 z-p42-scontent-lht6-1.cdninstagram.com
0.0.0.0 z-p42-scontent-los2-1.cdninstagram.com
0.0.0.0 z-p42-scontent-mad1-1.cdninstagram.com
0.0.0.0 z-p42-scontent-mia3-1.cdninstagram.com
0.0.0.0 z-p42-scontent-mia3-2.cdninstagram.com
0.0.0.0 z-p42-scontent-mrs1-1.cdninstagram.com
0.0.0.0 z-p42-scontent-msp1-1.cdninstagram.com
0.0.0.0 z-p42-scontent-mxp1-1.cdninstagram.com
0.0.0.0 z-p42-scontent-nrt1-1.cdninstagram.com
0.0.0.0 z-p42-scontent-ort2-1.cdninstagram.com
0.0.0.0 z-p42-scontent-ort2-2.cdninstagram.com
0.0.0.0 z-p42-scontent-sea1-1.cdninstagram.com
0.0.0.0 z-p42-scontent-sin2-1.cdninstagram.com
0.0.0.0 z-p42-scontent-sin2-2.cdninstagram.com
0.0.0.0 z-p42-scontent-sin6-1.cdninstagram.com
0.0.0.0 z-p42-scontent-sin6-2.cdninstagram.com
0.0.0.0 z-p42-scontent-sjc3-1.cdninstagram.com
0.0.0.0 z-p42-scontent-sof1-1.cdninstagram.com
0.0.0.0 z-p42-scontent-syd2-1.cdninstagram.com
0.0.0.0 z-p42-scontent-vie1-1.cdninstagram.com
0.0.0.0 z-p42-scontent-waw1-1.cdninstagram.com
0.0.0.0 z-p42-scontent-yyz1-1.cdninstagram.com
0.0.0.0 z-p42-scontent.cdninstagram.com
0.0.0.0 z-p42-static.cdninstagram.com

**Comment by Sinfonietta** [comment]
Thank you @me-ch these have all been added.
