### ISSUE TITLE
New to this

### ISSUE THREAD

**Issue by Yodatoo** [Sinfonietta/hostfiles#98]
How can I add new domains to the list?
(Sorry, I accidentally created a fork. Probably the wrong way, I think. Didn't add anything yet though.)

**Comment by Sinfonietta** [comment]
It's easy :-)

Try this:  make changes to your local fork.  Push them up to your repo, and you'll see a button to submit your changes to me as a pull request.

I won't bite :-)

**Comment by Yodatoo** [comment]
I've learnt how to edit. Then I guess I'm to choose "Create a new 
branch for this commit and start a pull request."
Oh, well. Let me just do it, and I suppose any mistake is not going 
to ruin anything.

**Comment by Yodatoo** [comment]
Did I do it right? Should I click "Merge pull request"?

**Comment by spirillen** [comment]
After a quick review of your work, you should point your MR target to Sinfonietta/hostfiles@master you should be able to do this by editing https://github.com/Yodatoo/hostfiles/pull/1

**Comment by Yodatoo** [comment]
> 
> 
> After a quick review of your work, you should point your MR target to Sinfonietta/hostfiles@master you should be able to do this by editing [Yodatoo#1](https://github.com/Yodatoo/hostfiles/pull/1)

And do I **_edit_** [Yodatoo#1](https://github.com/Yodatoo/hostfiles/pull/1)?
What or Which is "MR target"?

**Comment by Yodatoo** [comment]
Should I just give you a list instead?
Like this:
**PORN**
www.searchcelebrityhd.com
lustcinema.com
www.pascalssubsluts.com
lp.21naturals.com
www.bestpornbabes.com
www.azporncomics.com
jodic-forum.org
www.viewgals.com

**Comment by thomasmerz** [comment]
> Should I just give you a list instead?

All domains that @Yodatoo mentioned are already in the porn list:
```
🦎 ✔ ~/temp/PRs/fork-hostfiles [remove_non_domain_entries|✔]
22:57 $ ack www.searchcelebrityhd.com
pornography-hosts
22296:0.0.0.0 www.searchcelebrityhd.com
🦎 ✔ ~/temp/PRs/fork-hostfiles [remove_non_domain_entries|✔]
22:59 $ ack lustcinema.com
pornography-hosts
9885:0.0.0.0 lustcinema.com
🦎 ✔ ~/temp/PRs/fork-hostfiles [remove_non_domain_entries|✔]
23:00 $ ack www.pascalssubsluts.com
pornography-hosts
21599:0.0.0.0 www.pascalssubsluts.com
🦎 ✔ ~/temp/PRs/fork-hostfiles [remove_non_domain_entries|✔]
23:00 $ ack lp.21naturals.com
pornography-hosts
9857:0.0.0.0 lp.21naturals.com
🦎 ✔ ~/temp/PRs/fork-hostfiles [remove_non_domain_entries|✔]
23:00 $ ack www.bestpornbabes.com
pornography-hosts
19285:0.0.0.0 www.bestpornbabes.com
🦎 ✔ ~/temp/PRs/fork-hostfiles [remove_non_domain_entries|✔]
23:00 $ ack www.azporncomics.com
pornography-hosts
19192:0.0.0.0 www.azporncomics.com
🦎 ✔ ~/temp/PRs/fork-hostfiles [remove_non_domain_entries|✔]
23:00 $ ack jodic-forum.org
pornography-hosts
8898:0.0.0.0 jodic-forum.org
🦎 ✔ ~/temp/PRs/fork-hostfiles [remove_non_domain_entries|✔]
23:00 $ ack www.viewgals.com
pornography-hosts
23046:0.0.0.0 www.viewgals.com
🦎 ✔ ~/temp/PRs/fork-hostfiles [remove_non_domain_entries|✔]
23:00 $
```
@Sinfonietta , please close this issue.
