### ISSUE TITLE
i love to block porn

### ISSUE THREAD

**Issue by Danilopereira82** [Sinfonietta/hostfiles#99]
https://sukebei.tordl.com/
http://pronpic.org/
https://pornolab.net
http://jpbabe.com/
https://jav.sh/
https://javdock.net/
https://jav.plus/
http://javjh.com
http://javxy.com/
http://unicorn.wereanimal.net

**Comment by Sinfonietta** [comment]
Thank you @Danilopereira82 these are now added.

**Comment by spirillen** [comment]
`unicorn.wereanimal.net` no such host...

```
dig unicorn.wereanimal.net -p 5302

; <<>> DiG 9.16.1 <<>> +nocookie unicorn.wereanimal.net -p 5302
;; global options: +cmd
;; connection timed out; no servers could be reached
```

`sukebei.tordl.com` is hijacked by [parkingcrew](https://www.mypdns.org/T33)
![image](https://user-images.githubusercontent.com/44526987/79078252-56a33100-7d07-11ea-8192-9f31ea34dfc9.png)

<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +42 |  |  | sukebei.tordl.com | 1 | image | `http://sukebei.tordl.com/favicon.ico` |
| +42 |  |  | sukebei.tordl.com | 3 | image | `http://i.cdnpark.com/themes/registrar/images/logo_namecheap.png` |
| +42 | \|\|parkingcrew.net^$3p | -- | sukebei.tordl.com | 3 | script | `http://parkingcrew.net/jsparkcaf.php?regcn=243142&_v=2&_h=sukebei.tordl.com&_t=1586720891153` |
| +42 |  |  | sukebei.tordl.com | 3 | image | `http://i.cdnpark.com/themes/registrar/images/logo_namecheap.png` |
| +42 |  |  | sukebei.tordl.com | 3 | css | `http://i.cdnpark.com/themes/registrar/style_namecheap.css` |
| +42 |  |  | sukebei.tordl.com | 3 | css | `http://i.cdnpark.com/themes/assets/style.css` |
| +41 |  |  | sukebei.tordl.com | 1 | doc | `http://sukebei.tordl.com/` |
| +1 |  |  | tordl.com | 1 | image | `http://tordl.com/favicon.ico` |
| +1 |  |  | tordl.com | 3 | image | `http://i.cdnpark.com/themes/registrar/images/logo_namecheap.png` |
| +1 | \|\|parkingcrew.net^$3p | -- | tordl.com | 3 | script | `http://parkingcrew.net/jsparkcaf.php?regcn=243142&_v=2&_h=tordl.com&_t=1586720850216` |
| +1 |  |  | tordl.com | 3 | image | `http://i.cdnpark.com/themes/registrar/images/logo_namecheap.png` |
| +1 |  |  | tordl.com | 3 | css | `http://i.cdnpark.com/themes/registrar/style_namecheap.css` |
| +1 |  |  | tordl.com | 3 | css | `http://i.cdnpark.com/themes/assets/style.css` |
| +0 |  |  | tordl.com | 1 | doc | `http://tordl.com/` |
</details>

**Comment by Danilopereira82** [comment]
![Captura de tela_2020-04-12_21-36-35](https://user-images.githubusercontent.com/20802412/79083618-f15b3a00-7d1e-11ea-8d7c-1cfe881d729a.png)

the site is working well

**Comment by spirillen** [comment]
Cool but it didn't for me at that time, but seems like I've found the reason :unamused:
